// <auto-generated />
using System;
using CatAndDogServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CatAndDogServer.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200906184516_AdNameToPet")]
    partial class AdNameToPet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CatAndDogServer.Models.Cat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumNarodenia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PetOwnerId")
                        .HasColumnType("int");

                    b.Property<int>("PocetKrmeni")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetOwnerId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0
                        },
                        new
                        {
                            Id = 2,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0
                        },
                        new
                        {
                            Id = 3,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0
                        },
                        new
                        {
                            Id = 4,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0
                        },
                        new
                        {
                            Id = 5,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0
                        },
                        new
                        {
                            Id = 6,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0
                        },
                        new
                        {
                            Id = 7,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0
                        },
                        new
                        {
                            Id = 8,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0
                        },
                        new
                        {
                            Id = 9,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0
                        },
                        new
                        {
                            Id = 10,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0
                        },
                        new
                        {
                            Id = 11,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0
                        },
                        new
                        {
                            Id = 12,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0
                        },
                        new
                        {
                            Id = 13,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0
                        },
                        new
                        {
                            Id = 14,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0
                        },
                        new
                        {
                            Id = 15,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0
                        });
                });

            modelBuilder.Entity("CatAndDogServer.Models.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumNarodenia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PetOwnerId")
                        .HasColumnType("int");

                    b.Property<int>("PocetKrmeni")
                        .HasColumnType("int");

                    b.Property<int>("PocetUhriznuti")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetOwnerId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0,
                            PocetUhriznuti = 0
                        },
                        new
                        {
                            Id = 2,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0,
                            PocetUhriznuti = 0
                        },
                        new
                        {
                            Id = 3,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0,
                            PocetUhriznuti = 0
                        },
                        new
                        {
                            Id = 4,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0,
                            PocetUhriznuti = 0
                        },
                        new
                        {
                            Id = 5,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0,
                            PocetUhriznuti = 0
                        },
                        new
                        {
                            Id = 6,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0,
                            PocetUhriznuti = 0
                        },
                        new
                        {
                            Id = 7,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0,
                            PocetUhriznuti = 0
                        },
                        new
                        {
                            Id = 8,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0,
                            PocetUhriznuti = 0
                        },
                        new
                        {
                            Id = 9,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0,
                            PocetUhriznuti = 0
                        },
                        new
                        {
                            Id = 10,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0,
                            PocetUhriznuti = 0
                        },
                        new
                        {
                            Id = 11,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0,
                            PocetUhriznuti = 0
                        },
                        new
                        {
                            Id = 12,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0,
                            PocetUhriznuti = 0
                        },
                        new
                        {
                            Id = 13,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0,
                            PocetUhriznuti = 0
                        },
                        new
                        {
                            Id = 14,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0,
                            PocetUhriznuti = 0
                        },
                        new
                        {
                            Id = 15,
                            DatumNarodenia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetOwnerId = 1,
                            PocetKrmeni = 0,
                            PocetUhriznuti = 0
                        });
                });

            modelBuilder.Entity("CatAndDogServer.Models.PetOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PetOwners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Osada Plavecky Svrtok",
                            FullName = "Chovna stanica"
                        });
                });

            modelBuilder.Entity("CatAndDogServer.Models.Cat", b =>
                {
                    b.HasOne("CatAndDogServer.Models.PetOwner", "Owner")
                        .WithMany()
                        .HasForeignKey("PetOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CatAndDogServer.Models.Dog", b =>
                {
                    b.HasOne("CatAndDogServer.Models.PetOwner", "Owner")
                        .WithMany()
                        .HasForeignKey("PetOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
